import Head from 'next/head'
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Header  */}
      <Header />
      {/* Navbar  */}
      <Navbar />

      {/* Movies  */}
    </>
  );
}
