import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="text-bold bg-red-500">Search</div>

      {/* Header  */}

      {/* Navbar  */}

      {/* Movies  */}
    </>
  );
}
